# Generated by Django 5.0.2 on 2024-03-15 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0003_alter_task_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='deadline',
        ),
    ]
