# Generated by Django 5.0.2 on 2024-03-16 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0005_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
