# Generated by Django 5.0.2 on 2024-03-18 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0009_project_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='members',
        ),
    ]
