# Generated by Django 5.0.2 on 2024-03-19 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0013_alter_project_project_color_alter_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(db_column='project', null=True, on_delete=django.db.models.deletion.CASCADE, to='to_do_list.project', to_field='name'),
        ),
    ]
