# Generated by Django 5.0.2 on 2024-03-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('summ', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('price_for_one', models.FloatField(blank=True, null=True)),
                ('full_price', models.FloatField(blank=True, null=True)),
                ('margue', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DONE', 'Оплачено'), ('WAITING', 'Ожидает оплаты'), ('DELIVERY_PAY', 'Наложенный платеж'), ('NOSTATUS', 'Информация отсутствует')], default='NOSTATUS', max_length=20)),
            ],
        ),
    ]
