# Generated by Django 5.0.2 on 2024-03-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sells', '0002_sell_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
